### ISSUE TITLE
When I added the base attribute during the build phase, I found that the build product was missing the base prefix

### ISSUE THREAD

**Issue by RAGGA-TIME** [sumsolution/vite-plugin-svg-to-font#7]
When I added the base attribute during the build phase, I found that the build product was missing the base prefix
![image](https://user-images.githubusercontent.com/46967109/221455648-79ae0313-f9da-46d3-945e-0cb23cebd684.png)
![image](https://user-images.githubusercontent.com/46967109/221457148-2ab52ad7-5102-4d46-9b1a-a418634b04aa.png)
can be compatible？😄

**Comment by summer-jordan** [comment]
Thank you for reporting this! Sorry for the delay getting back to you, for some reason I was not notified of this issue. I will take a look today and see what I can do.

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RAGGA-TIME** [comment]
> Thank you for reporting this! Sorry for the delay getting back to you, for some reason I was not notified of this issue. I will take a look today and see what I can do.

Thank you! 👍

**Comment by RAGGA-TIME** [comment]
![image](https://user-images.githubusercontent.com/46967109/235037632-afdf7b96-823a-402b-94fe-a871496a0136.png)
hello~
I see the package generated by the github version log is valid

But I see on npm that there is no “base”

Could you please help to update the package on npm~
